### ISSUE TITLE
Autofac.Extras.NHibernate

### ISSUE THREAD

**Issue by cuibty** [autofac/Autofac.Extras.NHibernate#1]
Autofac.Extras.NHibernate what is the use in Autofac well?

Dependency injection ？

**Comment by tillig** [comment]
As noted in the readme, this is the Autofac implementation of the NHibernate factories that allow for dependency injection into entities and NHibernate objects.

Note that this was sort of a "drive-by" contribution and none of the current maintainers are NHibernate users so we can't really provide guidance on how to integrate this package. It is also in maintenance mode so no new features will be added.

**Comment by cuibty** [comment]
thanks
