### ISSUE TITLE
Support for .NET Standard and NHibernate 5.1+

### ISSUE THREAD

**Issue by TheDanielDoyle** [autofac/Autofac.Extras.NHibernate#4]
Please can you introduce support for .NET Standard and NHibernate 5.1+

**Comment by tillig** [comment]
As noted [in the README](https://github.com/autofac/Autofac.Extras.NHibernate/blob/master/README.md):

> This package is in maintenance-only mode. Bug fixes may be addressed and Autofac compatibility may be checked but no new features will be added.

You are free to take ownership of this project if that would help. You could fork it to your own repo, continue development, and we'd be happy to put a note in the README directing folks to you.

**Comment by EngSayed** [comment]
@TheDanielDoyle, Have you found an alternative solution ?
